Mark post as read after viewing the image or voting
gkasdorf/memmy pull request #202
Opened 2023-06-28 04:54 UTC by ktgd

2023-06-28 05:53 UTC, gkasdorf commented on components/hooks/feeds/useFeedItem.ts
> +  const setPostRead = () => {
added this to mark the posts as read in the state

2023-06-28 05:54 UTC, gkasdorf commented on components/hooks/feeds/useFeedItem.ts
> +      lemmyInstance.markPostAsRead({
use `setPostRead` to update the post in state

2023-06-28 05:56 UTC, gkasdorf commented on components/ui/ContentView.tsx
>    const onImagePress = () => {
use `feedItem.setPostRead()` from `FeedItem.tsx`. Should just pass the function into ContentView with a prop.

2023-06-28 05:57 UTC, gkasdorf commented on components/ui/Feed/CompactFeedItem/CompactFeedItemThumbnail.tsx
>    const onImagePress = () => {
Same thing here. Just use `feedItem.setPostRead()`

2023-06-28 05:57 UTC, gkasdorf requested changes
Mark the post as read in state. I have moved the logic in the on post press handler to a separate function, so you can call that where needed.

2023-06-28 06:03 UTC, gkasdorf commented
Like I said in the reviews, we need to make sure the state gets updated whenever we perform those actions. Otherwise it will only reflect on Lemmy and you'll need to refresh for the changes to be visible.

Also, I added a screen in Settings for you. Can we fill this out and have different settings for these? Some people don't seem to want image viewing to equate to reading, but others do. So I think it would be a good idea for this to be a toggle. Probably with these settings:

1. Post press is read
2. Image view is read
3. Post vote is read

All you need to add in `settingsSlice.tsx` is the options to `SettingsState` interface (i.e. `markReadOn:boolean`) and add the initial setting to the initial state. This will automatically update user settings on next load with the new values.

If you have questions let me know. I'd work on it myself but have other things I am working on right now.

Thanks!

2023-06-28 07:48 UTC, ktgd commented
Thanks for the tips and suggestions. I'll work on implementing the changes tomorrow!

2023-06-29 04:54 UTC, ktgd commented
Those changes have been implemented and I added options to the settings for:
- Mark Read on Post Open
- Mark Read on Image View
- Mark Read on Vote

Everything is working for the Compact view, but Post Open and Vote aren't being triggered on the Normal view. I will look into that tomorrow. 

Thanks!

2023-06-29 08:34 UTC, gkasdorf approved these changes

2023-06-29 08:35 UTC, gkasdorf commented
Everything looks good now! Made a [a few changes](https://github.com/gkasdorf/memmy/pull/202/commits/1eec15a66ebae81fc7fdf365c1c74401cca3fa2e) to how it performs the update when liking the post (should make the like post request before the read post request). Also added post.read to the memo, but that was my fault not yours.

Thanks for this one!

2023-06-29 08:35 UTC, merged